version: "3.9"

services:
  mongo_db:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongo_db:/data/db # convention
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  # backend service
  backend_dev:
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    ports:
      - 8080:8080
    environment:
      PORT: 8080
      MONGO_URL: mongodb://root:example@mongo_db:27017
    links:
      - mongo_db
    depends_on:
      - mongo_db

   # frontend service
  frontend_dev:
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - backend_dev
      - mongo_db
  
volumes:
  mongo_db:
    name: mongo-volume